FROM amd64/python:3.7-slim-buster

WORKDIR /app

# UPGRADE pip3
RUN pip3 install --upgrade pip

COPY requirements.txt ./
RUN pip install -r requirements.txt
EXPOSE 8000

COPY . .

CMD [ "python3", "-u", "./main.py" ]